pokemon_data = [
    {'number': 1, 'name': 'Bulbasaur', 'types': ['Planta', 'Veneno'], 'weaknesses': ['Fuego', 'Hielo', 'Volador', 'Psíquico'], 'mega': False, 'gigamax': False},
    {'number': 2, 'name': 'Ivysaur', 'types': ['Planta', 'Veneno'], 'weaknesses': ['Fuego', 'Hielo', 'Volador', 'Psíquico'], 'mega': False, 'gigamax': False},
    {'number': 3, 'name': 'Venusaur', 'types': ['Planta', 'Veneno'], 'weaknesses': ['Fuego', 'Hielo', 'Volador', 'Psíquico'], 'mega': True, 'gigamax': True},
    {'number': 4, 'name': 'Charmander', 'types': ['Fuego'], 'weaknesses': ['Agua', 'Tierra', 'Roca'], 'mega': False, 'gigamax': False},
    {'number': 5, 'name': 'Charmeleon', 'types': ['Fuego'], 'weaknesses': ['Agua', 'Tierra', 'Roca'], 'mega': False, 'gigamax': False},
    {'number': 6, 'name': 'Charizard', 'types': ['Fuego', 'Volador'], 'weaknesses': ['Agua', 'Eléctrico', 'Roca'], 'mega': True, 'gigamax': True},
    {'number': 25, 'name': 'Pikachu', 'types': ['Eléctrico'], 'weaknesses': ['Tierra'], 'mega': False, 'gigamax': True},
    {'number': 52, 'name': 'Meowth', 'types': ['Normal'], 'weaknesses': ['Lucha'], 'mega': False, 'gigamax': True},
    {'number': 81, 'name': 'Magnemite', 'types': ['Eléctrico', 'Acero'], 'weaknesses': ['Fuego', 'Lucha', 'Tierra'], 'mega': False, 'gigamax': False},
    {'number': 82, 'name': 'Magneton', 'types': ['Eléctrico', 'Acero'], 'weaknesses': ['Fuego', 'Lucha', 'Tierra'], 'mega': False, 'gigamax': False},
    {'number': 92, 'name': 'Gastly', 'types': ['Fantasma', 'Veneno'], 'weaknesses': ['Fantasma', 'Siniestro', 'Psíquico', 'Tierra'], 'mega': False, 'gigamax': False},
    {'number': 93, 'name': 'Haunter', 'types': ['Fantasma', 'Veneno'], 'weaknesses': ['Fantasma', 'Siniestro', 'Psíquico', 'Tierra'], 'mega': False, 'gigamax': False},
    {'number': 94, 'name': 'Gengar', 'types': ['Fantasma', 'Veneno'], 'weaknesses': ['Fantasma', 'Siniestro', 'Psíquico', 'Tierra'], 'mega': True, 'gigamax': True},
    {'number': 125, 'name': 'Electabuzz', 'types': ['Eléctrico'], 'weaknesses': ['Tierra'], 'mega': False, 'gigamax': False},
    {'number': 126, 'name': 'Magmar', 'types': ['Fuego'], 'weaknesses': ['Agua', 'Tierra', 'Roca'], 'mega': False, 'gigamax': False},
    {'number': 133, 'name': 'Eevee', 'types': ['Normal'], 'weaknesses': ['Lucha'], 'mega': False, 'gigamax': True},
    {'number': 135, 'name': 'Jolteon', 'types': ['Eléctrico'], 'weaknesses': ['Tierra'], 'mega': False, 'gigamax': False},
    {'number': 136, 'name': 'Flareon', 'types': ['Fuego'], 'weaknesses': ['Agua', 'Tierra', 'Roca'], 'mega': False, 'gigamax': False},
    {'number': 143, 'name': 'Snorlax', 'types': ['Normal'], 'weaknesses': ['Lucha'], 'mega': False, 'gigamax': True},
    {'number': 151, 'name': 'Mew', 'types': ['Psíquico'], 'weaknesses': ['Bicho', 'Fantasma', 'Siniestro'], 'mega': False, 'gigamax': False},
    {'number': 155, 'name': 'Cyndaquil', 'types': ['Fuego'], 'weaknesses': ['Agua', 'Tierra', 'Roca'], 'mega': False, 'gigamax': False},
    {'number': 157, 'name': 'Typhlosion', 'types': ['Fuego'], 'weaknesses': ['Agua', 'Tierra', 'Roca'], 'mega': False, 'gigamax': False},
    {'number': 208, 'name': 'Steelix', 'types': ['Acero', 'Tierra'], 'weaknesses': ['Fuego', 'Agua', 'Lucha', 'Tierra'], 'mega': True, 'gigamax': False},
    {'number': 227, 'name': 'Skarmory', 'types': ['Acero', 'Volador'], 'weaknesses': ['Fuego', 'Eléctrico'], 'mega': False, 'gigamax': False},
    {'number': 254, 'name': 'Sceptile', 'types': ['Planta'], 'weaknesses': ['Fuego', 'Hielo', 'Volador', 'Psíquico', 'Bicho'], 'mega': True, 'gigamax': False},
    {'number': 257, 'name': 'Blaziken', 'types': ['Fuego', 'Lucha'], 'weaknesses': ['Agua', 'Volador', 'Psíquico', 'Tierra'], 'mega': True, 'gigamax': False},
    {'number': 384, 'name': 'Rayquaza', 'types': ['Dragón', 'Volador'], 'weaknesses': ['Hielo', 'Roca', 'Dragón', 'Hada'], 'mega': True, 'gigamax': False},
    {'number': 445, 'name': 'Garchomp', 'types': ['Dragón', 'Tierra'], 'weaknesses': ['Hielo', 'Dragón', 'Hada'], 'mega': True, 'gigamax': False},
    {'number': 448, 'name': 'Lucario', 'types': ['Lucha', 'Acero'], 'weaknesses': ['Fuego', 'Lucha', 'Tierra'], 'mega': True, 'gigamax': False},
    {'number': 635, 'name': 'Hydreigon', 'types': ['Siniestro', 'Dragón'], 'weaknesses': ['Hada', 'Lucha', 'Bicho', 'Dragón', 'Hielo'], 'mega': False, 'gigamax': False},
    {'number': 668, 'name': 'Pyroar', 'types': ['Fuego', 'Normal'], 'weaknesses': ['Agua', 'Lucha', 'Tierra', 'Roca'], 'mega': False, 'gigamax': False},
    {'number': 679, 'name': 'Honedge', 'types': ['Acero', 'Fantasma'], 'weaknesses': ['Fuego', 'Tierra', 'Fantasma', 'Siniestro'], 'mega': False, 'gigamax': False},
    {'number': 681, 'name': 'Aegislash', 'types': ['Acero', 'Fantasma'], 'weaknesses': ['Fuego', 'Tierra', 'Fantasma', 'Siniestro'], 'mega': False, 'gigamax': False},
    {'number': 697, 'name': 'Tyrantrum', 'types': ['Roca', 'Dragón'], 'weaknesses': ['Hielo', 'Lucha', 'Tierra', 'Acero', 'Dragón', 'Hada'], 'mega': False, 'gigamax': False},
    {'number': 745, 'name': 'Lycanroc', 'types': ['Roca'], 'weaknesses': ['Agua', 'Planta', 'Lucha', 'Tierra', 'Acero'], 'mega': False, 'gigamax': False},
    {'number': 809, 'name': 'Melmetal', 'types': ['Acero'], 'weaknesses': ['Fuego', 'Lucha', 'Tierra'], 'mega': False, 'gigamax': True},
    {'number': 812, 'name': 'Rillaboom', 'types': ['Planta'], 'weaknesses': ['Fuego', 'Hielo', 'Volador', 'Psíquico', 'Bicho'], 'mega': False, 'gigamax': True},
    {'number': 815, 'name': 'Cinderace', 'types': ['Fuego'], 'weaknesses': ['Agua', 'Tierra', 'Roca'], 'mega': False, 'gigamax': True},
    {'number': 818, 'name': 'Inteleon', 'types': ['Agua'], 'weaknesses': ['Eléctrico', 'Planta'], 'mega': False, 'gigamax': True},
    {'number': 823, 'name': 'Corviknight', 'types': ['Volador', 'Acero'], 'weaknesses': ['Fuego', 'Eléctrico'], 'mega': False, 'gigamax': True},
    {'number': 888, 'name': 'Zacian', 'types': ['Hada', 'Acero'], 'weaknesses': ['Fuego', 'Tierra'], 'mega': False, 'gigamax': False},
    {'number': 892, 'name': 'Urshifu', 'types': ['Lucha', 'Siniestro'], 'weaknesses': ['Lucha', 'Volador', 'Hada'], 'mega': False, 'gigamax': True},
    {'number': 902, 'name': 'Basculegion', 'types': ['Agua', 'Fantasma'], 'weaknesses': ['Planta', 'Eléctrico', 'Fantasma', 'Siniestro'], 'mega': False, 'gigamax': False},
    {'number': 937, 'name': 'Ceruledge', 'types': ['Fuego', 'Fantasma'], 'weaknesses': ['Agua', 'Tierra', 'Roca', 'Fantasma', 'Siniestro'], 'mega': False, 'gigamax': False},
]