character_data = [
    ("Luke Skywalker", {"episodes": 6}),
    ("Darth Vader", {"episodes": 7}),
    ("Yoda", {"episodes": 7}),
    ("Boba Fett", {"episodes": 4}),
    ("C-3PO", {"episodes": 9}),
    ("Leia", {"episodes": 7}),
    ("Rey", {"episodes": 3}),
    ("Kylo Ren", {"episodes": 3}),
    ("Chewbacca", {"episodes": 7}),
    ("Han Solo", {"episodes": 5}),
    ("R2-D2", {"episodes": 9}),
    ("BB-8", {"episodes": 3}),
]

edge_data = [
    ("Luke Skywalker", "Darth Vader", 4),
    ("Luke Skywalker", "Leia", 5),
    ("Luke Skywalker", "Han Solo", 4),
    ("Luke Skywalker", "C-3PO", 6),
    ("Luke Skywalker", "R2-D2", 6),
    ("Luke Skywalker", "Yoda", 4),
    ("Han Solo", "Leia", 5),
    ("Han Solo", "Chewbacca", 5),
    ("Han Solo", "C-3PO", 5),
    ("C-3PO", "R2-D2", 9),
    ("C-3PO", "Leia", 7),
    ("C-3PO", "Darth Vader", 5),
    ("Yoda", "R2-D2", 5),
    ("Yoda", "Darth Vader", 4),
    ("Boba Fett", "Darth Vader", 2),
    ("Boba Fett", "Han Solo", 3),
    ("Rey", "Kylo Ren", 3),
    ("Rey", "BB-8", 3),
    ("Rey", "Leia", 3),
    ("BB-8", "Han Solo", 1),
    ("Kylo Ren", "Darth Vader", 1),
]